-- GENERATED by scripts/build-seed.mjs from content/seed/*.json — do not edit by hand.
-- Default copy. INSERT OR IGNORE keeps any value already edited in the admin.
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.name', 'ru', 'Сюзана Тевдорадзе', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.role', 'ru', 'AI / Technical Product Lead', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.description', 'ru', 'Продуктовая стратегия для AI- и дата-продуктов: проверить спрос, цену и экономику до того, как потрачены деньги.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.home', 'ru', 'Главная', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.pricing', 'ru', 'Цены', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.about', 'ru', 'Обо мне', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.contact', 'ru', 'Контакты', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.kicker', 'ru', 'AI / Technical Product Lead', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.title', 'ru', 'Понять, что стоит строить — до того как потрачены деньги', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.lead', 'ru', 'Меня зовут Сюзана Тевдорадзе. Я продакт-лид с техническим бэкграундом: веду AI- и дата-продукты от стратегии до запуска, консультирую и подключаюсь к командам.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.cta', 'ru', 'Бесплатный разговор, 20–40 минут', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.note', 'ru', 'Без питча и слайдов. Если по делу хватит одного разговора — этим и ограничимся.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.title', 'ru', 'С чем ко мне приходят', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.items', 'ru', '- Есть идея AI-продукта — и хочется понять, купит ли её кто-нибудь, **до** найма разработчиков.
- Продукт строится или запущен, но непонятно, за что готовы платить и сходится ли экономика, если честно посчитать токены и ручные шаги.
- AI-фича «почти работает» который месяц. Деньги уходят, а решение «докручивать или остановиться» никто не принимает.
- Продакта в команде нет: стратегию, бэклог и разговоры с пользователями тянет фаундер.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.title', 'ru', 'Три формата работы', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.inside_label', 'ru', 'Что внутри', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.title', 'ru', 'Проверка «строить или нет»', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.duration', 'ru', '2–3 недели, фиксированный объём', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.price', 'ru', 'от €3 500', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.body', 'ru', 'Для идеи или раннего продукта — на развилке перед большими тратами. На выходе письменный вердикт: **строить / подождать / переделать замысел**, с источником под каждым выводом и план самого дешёвого следующего теста. Иногда вердикт — «не строить». Это решение, принятое до потраченных денег.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.inside', 'ru', '- Разбор отзывов на конкурентов и на то, чем люди обходятся сейчас
- 5–8 интервью с вашей аудиторией — включая тех, кто не купил
- Карта рисков: какое предположение самое опасное
- Экономика на одну страницу: конверсия, стоимость клиента, стоимость эксплуатации на пользователя', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.title', 'ru', 'Discovery-спринт', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.duration', 'ru', '4–6 недель, до плана запуска', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.price', 'ru', 'от €7 000', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.body', 'ru', 'Для тех, кто решил строить и хочет проверенный план, а не список фич. Всё из проверки — глубже, плюс позиционирование, тест цены на реальном трафике, скоуп MVP и роадмап на 6–12 месяцев.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.inside', 'ru', '- Позиционирование: с чем вас на самом деле сравнивает покупатель
- Тест цены: страница с настоящей ценой и заранее записанным порогом остановки
- Скоуп MVP: что режем, чтобы проверить главный риск
- Приоритизированный роадмап на 6–12 месяцев', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.title', 'ru', 'AI / Technical Product Lead в вашей команде', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.duration', 'ru', '1–2 дня в неделю, первый месяц — пробный', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.price', 'ru', 'от €3 000 / мес', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.body', 'ru', 'Для команд, где продукт живёт, а владельца у него нет. Беру стратегию и роадмап, еженедельное discovery, метрики и экономику, разговоры со стейкхолдерами — и помогаю нанять постоянного продакта. Хорошая фракционная работа заканчивается тем, что я становлюсь не нужна.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.inside', 'ru', '- Стратегия и роадмап
- Еженедельное discovery и метрики
- Экономика решений, включая стоимость AI
- Путь от прототипа до production', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.footnote', 'ru', 'Разовая консультация (€150) и почасовая работа (от €100/час) — на странице [«Цены»](/ru/pricing).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.title', 'ru', 'Как это устроено', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.steps', 'ru', '- Бесплатный разговор, 20–40 минут.
- Письмо с фиксированными объёмом, сроком и ценой. Никаких «посмотрим по ходу».
- Работа с коротким апдейтом раз в неделю.
- Финальная сессия и письменный отчёт.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.principles', 'ru', '- Порог остановки записываем до старта: что считать неудачей, формулируется заранее.
- Я не продаю часы — я продаю ответ на вопрос и следующий шаг.
- Каждый вывод проверяем: цитата из отзыва, запись интервью, цифра с источником и датой. Если результат нельзя проверить — это не результат.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('fit.title', 'ru', 'Кому подойдёт — и кому нет', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('fit.body', 'ru', 'Чаще всего — фаундерам до запуска и командам, у которых AI- или дата-продукт не сходится: с деньгами, метриками или ожиданиями. Отрасль значит меньше, чем кажется: метод один — проверить спрос, цену и экономику до кода.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('fit.not', 'ru', 'Я не подойду, если нужен исполнитель, который молча пишет фичи по списку, или агентство на разработку. Моя работа — до и вокруг разработки: что строить, почём и зачем.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('cta.title', 'ru', 'Разобрать ваш продукт?', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('cta.body', 'ru', 'Напишите или забронируйте бесплатные 20–40 минут.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.title', 'ru', 'Цены', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.intro', 'ru', 'Все цены — ориентиры «от»: точную цену фиксируем письменно после бесплатного знакомства, вместе с объёмом и сроком. Дальше она не меняется.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.columns', 'ru', 'Формат | Срок | Цена', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.rows', 'ru', 'Знакомство | 20–40 минут | бесплатно
Консультация с письменным резюме | 60–90 минут | €150
Почасовая работа | по договорённости; первая задача от 2 часов | от €100 / час
Проверка «строить или нет» | 2–3 недели, фикс-скоуп | от €3 500
Discovery-спринт | 4–6 недель | от €7 000
AI / Technical Product Lead в команде | 1 день в неделю; первый месяц пробный | от €3 000 / мес
 | 2 дня в неделю | от €5 500 / мес
Фултайм-контракт | от 3 месяцев | по запросу', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.note', 'ru', 'Знакомство бесплатно один раз: дальше любой разбор — это работа, и она оплачивается. Суммы — по инвойсу, до налогов.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.title', 'ru', 'Обо мне', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.bio', 'ru', 'Технический продакт-лид в AI- и дата-продуктах. Веду продукт от стратегии до запуска: руковожу командой, вывожу AI-функции в production, считаю экономику решений — включая стоимость моделей — и снижаю затраты там, где они не создают ценности.

Моя любимая часть работы — понять, что стоит строить, до того как потрачены деньги.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.credentials', 'ru', 'AI / Technical Product Lead — стратегия, discovery, доставка', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.cv_label', 'ru', 'Скачать CV (PDF)', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.links_label', 'ru', 'Где я ещё', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.title', 'ru', 'Контакты', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.body', 'ru', 'Захотите разобрать свой продукт — забронируйте бесплатные 20–40 минут или напишите.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.booking_label', 'ru', 'Забронировать разговор', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.email_label', 'ru', 'Почта', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_title', 'ru', 'Или коротко здесь', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_name', 'ru', 'Имя', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_email', 'ru', 'Email', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_message', 'ru', 'Коротко о ситуации', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_send', 'ru', 'Отправить', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_ok', 'ru', 'Спасибо — отвечу в течение двух рабочих дней.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_error', 'ru', 'Не получилось отправить. Напишите, пожалуйста, на почту.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.playful', 'ru', 'Балуюсь вайбкодингом — [здесь]({github}) — и этикой данных — [здесь]({channel}).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_line', 'ru', 'Канал про этику данных и продуктовый анализ — думать до того, как строить.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.linkedin_label', 'ru', 'LinkedIn', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.github_label', 'ru', 'GitHub', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_label', 'ru', 'Telegram-канал', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.title', 'ru', 'Такой страницы нет', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.body', 'ru', 'Вернуться на [главную](/ru/).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.name', 'en', 'Syuzana Tevdoradze', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.role', 'en', 'AI / Technical Product Lead', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.description', 'en', 'Product strategy for AI and data products: test demand, price and economics before the money is spent.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.home', 'en', 'Home', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.pricing', 'en', 'Pricing', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.about', 'en', 'About', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.contact', 'en', 'Contact', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.kicker', 'en', 'AI / Technical Product Lead', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.title', 'en', 'Know what''s worth building — before the money is spent', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.lead', 'en', 'I''m Syuzana Tevdoradze, a product lead with a technical background. I take AI and data products from strategy to launch, consult, and join teams hands-on.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.cta', 'en', 'Free call, 20–40 minutes', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.note', 'en', 'No pitch, no slides. If one conversation is enough, we stop there.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.title', 'en', 'What people come with', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.items', 'en', '- An AI product idea — and the question of whether anyone will buy it, **before** hiring developers.
- A product in build or already live, but no clarity on what customers will pay for, or whether the economics hold once you count tokens and manual steps honestly.
- An AI feature that has "almost worked" for months. Money keeps going out; nobody decides whether to push on or stop.
- No product owner on the team: strategy, backlog and user conversations all land on the founder.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.title', 'en', 'Three ways to work', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.inside_label', 'en', 'What''s inside', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.title', 'en', 'Build-or-not check', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.duration', 'en', '2–3 weeks, fixed scope', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.price', 'en', 'from €3,500', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.body', 'en', 'For an idea or an early product at the fork before big spending. You get a written verdict — **build / wait / rethink** — with a source behind every conclusion, and a plan for the cheapest next test. Sometimes the verdict is "don''t build". That''s a decision made before the money is spent.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.inside', 'en', '- Review mining: competitors, and whatever people use today
- 5–8 interviews with your audience — including those who didn''t buy
- Risk map: which assumption is the most dangerous
- One-page economics: conversion, cost per customer, cost to serve per user', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.title', 'en', 'Discovery sprint', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.duration', 'en', '4–6 weeks, through to a launch plan', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.price', 'en', 'from €7,000', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.body', 'en', 'For those who''ve decided to build and want a tested plan, not a feature list. Everything in the check, deeper — plus positioning, a price test on real traffic, MVP scope and a 6–12-month roadmap.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.discovery.inside', 'en', '- Positioning: what buyers actually compare you with
- Price test: a real-price page with a stop threshold written down in advance
- MVP scope: what we cut to test the main risk
- Prioritised 6–12-month roadmap', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.title', 'en', 'AI / Technical Product Lead on your team', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.duration', 'en', '1–2 days a week; the first month is a trial', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.price', 'en', 'from €3,000 / month', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.body', 'en', 'For teams whose product is alive but has no owner. I take strategy and roadmap, weekly discovery, metrics and economics, stakeholder conversations — and help hire your permanent product lead. Fractional work done well ends with me no longer being needed.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.inside', 'en', '- Strategy and roadmap
- Weekly discovery and metrics
- Decision economics, including the cost of AI
- The path from prototype to production', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.footnote', 'en', 'A one-off consultation (€150) and hourly work (from €100/hour) are on the [Pricing](/en/pricing) page.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.title', 'en', 'How it works', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.steps', 'en', '- A free call, 20–40 minutes.
- A letter with fixed scope, timeline and price. No "let''s see as we go".
- The work, with a short weekly update.
- A final session and a written report.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.principles', 'en', '- The stop threshold is written down before we start: what counts as failure is defined in advance.
- I don''t sell hours — I sell an answer to a question and the next step.
- Every conclusion is verifiable: a quote from a review, an interview recording, a number with a source and a date. If a result can''t be verified, it isn''t a result.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('fit.title', 'en', 'Who it''s for — and who it isn''t', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('fit.body', 'en', 'Most often: founders before launch, and teams whose AI or data product doesn''t add up — on money, metrics or expectations. Industry matters less than it seems: the method is the same — test demand, price and economics before code.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('fit.not', 'en', 'I''m not the right fit if you need someone to quietly ship features from a list, or a development agency. My work is before and around development: what to build, at what price, and why.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('cta.title', 'en', 'Want to take your product apart?', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('cta.body', 'en', 'Write to me, or book a free 20–40 minutes.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.title', 'en', 'Pricing', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.intro', 'en', 'All prices are "from" guides: the exact price is fixed in writing after the free intro call, together with scope and timeline. It doesn''t change after that.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.columns', 'en', 'Format | Duration | Price', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.rows', 'en', 'Intro call | 20–40 minutes | free
Consultation with a written summary | 60–90 minutes | €150
Hourly work | by agreement; first task from 2 hours | from €100 / hour
Build-or-not check | 2–3 weeks, fixed scope | from €3,500
Discovery sprint | 4–6 weeks | from €7,000
AI / Technical Product Lead on your team | 1 day a week; first month is a trial | from €3,000 / month
 | 2 days a week | from €5,500 / month
Full-time contract | from 3 months | on request', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.note', 'en', 'The intro call is free once; after that any analysis is work, and work is paid. Amounts are invoiced before taxes.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.title', 'en', 'About', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.bio', 'en', 'Technical product lead in AI and data products. I take a product from strategy to launch: lead the team, bring AI features to production, do the economics of decisions — including the cost of models — and cut spend where it creates no value.

My favourite part of the job is working out what''s worth building before the money is spent.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.credentials', 'en', 'AI / Technical Product Lead — strategy, discovery, delivery', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.cv_label', 'en', 'Download CV (PDF)', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.links_label', 'en', 'Elsewhere', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.title', 'en', 'Contact', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.body', 'en', 'Want to take your product apart? Book a free 20–40 minutes, or write.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.booking_label', 'en', 'Book a call', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.email_label', 'en', 'Email', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_title', 'en', 'Or briefly, right here', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_name', 'en', 'Name', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_email', 'en', 'Email', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_message', 'en', 'Briefly, what''s the situation?', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_send', 'en', 'Send', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_ok', 'en', 'Thank you — I''ll reply within two working days.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_error', 'en', 'Couldn''t send. Please email me instead.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.playful', 'en', 'I play around with vibecoding — [here]({github}) — and with data ethics — [here]({channel}).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_line', 'en', 'A channel on data ethics and product analysis — thinking before building.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.linkedin_label', 'en', 'LinkedIn', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.github_label', 'en', 'GitHub', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_label', 'en', 'Telegram channel', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.title', 'en', 'There''s no such page', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.body', 'en', 'Back to the [home page](/en/).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.email', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.linkedin', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.github', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.channel', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.booking_url', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
