-- GENERATED by scripts/build-seed.mjs from content/seed/*.json — do not edit by hand.
-- Default copy. INSERT OR IGNORE keeps any value already edited in the admin.
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.name', 'ru', 'Сюзана Тевдорадзе', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.role', 'ru', 'Technical Product Owner · AI и дата-продукты', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.description', 'ru', 'Технический продакт для AI- и дата-продуктов: решения о том, что строить, как довести до production и при какой экономике.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.situations', 'ru', 'Задачи', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.formats', 'ru', 'Форматы', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.process', 'ru', 'Как работаю', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.experience', 'ru', 'Опыт', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.pricing', 'ru', 'Цены', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.contact', 'ru', 'Контакты', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.role', 'ru', 'Technical Product Owner · AI и дата-продукты', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.title', 'ru', 'Стратегия и развитие AI-продуктов', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.lead', 'ru', 'Я продакт-лид с техническим бэкграундом. Работаю с AI-продуктами и продуктами на данных: определяю приоритеты, оцениваю экономику и технические ограничения, веду реализацию вместе с командой. Обычно начинаю с фокуса: функция продукта, основная боль, рынок и сегмент. Дальше расчёт, окупится ли продукт, цели (OKR/KPI) и роадмап. На этом основании основатель принимает решение о запуске, развитии или остановке.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.cta', 'ru', 'Записаться бесплатно', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.note', 'ru', 'Первая консультация, 20–40 минут онлайн: вы рассказываете задачу, я говорю, чем могу помочь и нужна ли вам вообще.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.contacts_label', 'ru', 'Связаться', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.title', 'ru', 'С чем ко мне приходят', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.items', 'ru', '- Перед запуском AI-продукта нужно оценить спрос, техническую реализуемость и экономику, чтобы принять решение об инвестициях.
- Нужен понятный план разработки: что делаем первым, что потом, сколько это стоит и по каким метрикам поймём, что получается.
- В продукт встраивают AI-функцию, например распознавание, рекомендации или ассистента. Сроки сдвигаются, качество не дотягивает до нужного, расходы на модели и разметку растут. Нужно решить, продолжать, менять подход или останавливать.
- Непонятно, за что клиенты готовы платить и окупается ли продукт с учётом инфраструктуры, разметки, ручной проверки и поддержки.
- В команде нет продакт-менеджера. Основателю или техническому руководителю нужна помощь с исследованиями, приоритетами и управлением разработкой.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.title', 'ru', 'Форматы работы', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.intro', 'ru', 'Два проектных формата и один в команде. Начинаем с бесплатной первой консультации, затем письменно фиксируем объём, срок и цену.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.involvement_label', 'ru', 'Что нужно от вас', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.result_label', 'ru', 'Результат', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.inside_label', 'ru', 'Что внутри', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.title', 'ru', 'Аудит действующего AI-продукта', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.duration', 'ru', '1–2 недели', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.body', 'ru', 'Разбираю качество моделей и данных, реальное использование и стоимость работы продукта. Нахожу, что мешает, и что можно не трогать.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.inside', 'ru', '- Что клиенты реально используют и за что платят, а что лежит мёртвым грузом
- Какую точность модели дают на реальных данных и где именно проваливаются
- Во что обходится каждый клиент: инфраструктура, разметка, ручная проверка, поддержка
- Что в архитектуре мешает развитию и в какой очередности это менять', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.involvement', 'ru', 'Доступ к системе, данным и метрикам; две-три встречи с командой.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.result', 'ru', 'План доработки: что чинить, что убрать, в какой очередности, с оценкой трудозатрат и стоимости эксплуатации. И вердикт: продолжать, менять подход или прекращать.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.title', 'ru', 'Продакт-лид на частичную занятость', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.duration', 'ru', '4 или 8 дней в месяц', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.body', 'ru', 'Беру продуктовую работу на себя: приоритеты, исследования, требования для разработчиков, приёмка результата, координация с командой.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.inside', 'ru', '- Приоритеты и роадмап
- Исследования и метрики
- Требования и приёмка
- Экономика решений, включая стоимость AI', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.involvement', 'ru', 'Зону ответственности и цели согласуем перед началом; начинаем с одного оплачиваемого месяца.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.result', 'ru', 'У продукта появляется владелец: решения принимаются, требования написаны, разработка идёт по плану. Когда придёт время, помогаю нанять постоянного продакта.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.title', 'ru', 'Как это устроено', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.steps', 'ru', '- Первая консультация, бесплатно, 20–40 минут: вы рассказываете задачу, я говорю, чем могу помочь.
- Письмо с объёмом, сроком и ценой. При согласованном объёме сумма не меняется.
- Работа с коротким апдейтом раз в неделю.
- Финальная встреча и письменный отчёт.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.principles', 'ru', '- До старта записываем, что будем считать неудачей.
- В отчёте отдельно отмечаю, что подтверждено данными, а что остаётся предположением.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.title', 'ru', 'Опыт', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.intro', 'ru', 'Несколько результатов последних лет. Компании не называю, подробности в CV.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.items', 'ru', '- AI-мониторинг для теплиц: из более чем десяти моделей оставили четыре рабочие, перестроили разметку. Средняя точность в production выросла с 0.6 до 0.9, ручной разметки стало меньше примерно на 95%.
- Мультитенантная инфраструктура: после перехода на общие сервисы облачные расходы на клиента снизились примерно в 10 раз, экономика стала положительной.
- Государственная аналитика: NLP-система для 200–250 тысяч обращений в год, которая делает классификацию, извлечение сущностей и маршрутизацию. Обработка ускорилась примерно в 5 раз, итоговое решение осталось за человеком.
- Данные о мобильности: после перехода с построчного хранения на векторное отчёт, который строился около трёх дней, стал строиться за полтора часа.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.types', 'ru', 'Чаще всего это компьютерное зрение и NLP в production, дата-платформы, легаси-системы и экономика AI-продуктов на ранней стадии.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.bio', 'ru', 'Я руководитель продукта с техническим опытом. Помогаю найти фокус продукта и понять, стоит ли его делать. Исследую ценность, рынок, аудиторию и конкурентов. Считаю, окупится ли продукт, и определяю, каким он должен быть технически. Составляю стратегию развития и сопровождаю разработку до запуска.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('card.qr_title', 'ru', 'Отсканируйте, чтобы сохранить контакт', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('card.qr_note', 'ru', 'Открывает vCard на телефоне, ничего не нужно набирать. Полезно, когда страницу видят на чужом экране.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.cv_label', 'ru', 'Скачать CV (PDF)', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.title', 'ru', 'Цены', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.intro', 'ru', 'Ставка **от €100 в час**, отдельные задачи от двух часов. Объём проекта оцениваю в часах заранее и фиксирую письменно.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.columns', 'ru', 'Формат | Объём | Срок', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.rows', 'ru', 'Первая консультация | 20–40 минут, бесплатно | –
Консультация | 1 час, €150 | в течение недели
Консультация с письменным разбором | от 3 часов, от €350 | в течение недели
Отдельная задача | от 2 часов | по договорённости
Аудит действующего AI-продукта | от 20 часов | 1–2 недели
Оценка нового продукта или направления | от 30 часов | 2–4 недели
Продакт-лид на частичную занятость | 4 или 8 дней в месяц | от 1 месяца
Полная занятость | полный день | по запросу', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.note', 'ru', 'Итоговую сумму, объём и срок фиксируем в письменном предложении после первой консультации. При согласованном объёме сумма не меняется. В предложении указано, добавляются ли налоги.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.title', 'ru', 'Контакты', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.body', 'ru', 'Напишите пару строк о задаче, отвечу в течение двух рабочих дней. Или сразу запишитесь на бесплатную первую консультацию.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.booking_label', 'ru', 'Записаться на бесплатную консультацию', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.email_label', 'ru', 'Почта', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_title', 'ru', 'Или коротко здесь', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_name', 'ru', 'Имя', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_email', 'ru', 'Email', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_message', 'ru', 'Коротко о ситуации', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_send', 'ru', 'Отправить', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_ok', 'ru', 'Спасибо. Отвечу в течение двух рабочих дней.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_error', 'ru', 'Не получилось отправить. Напишите, пожалуйста, на почту.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_unavailable', 'ru', 'Отправка через форму пока недоступна. Напишите мне:', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_line', 'ru', 'Канал про этику данных и продуктовый анализ.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.linkedin_label', 'ru', 'LinkedIn', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.github_label', 'ru', 'GitHub', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_label', 'ru', 'Telegram-канал', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.calendar_label', 'ru', 'Календарь', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.title', 'ru', 'Такой страницы нет', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.body', 'ru', 'Вернуться на [главную](/ru/).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_title', 'ru', 'Канал «Принимаю условия»', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_body', 'ru', 'Пишу про этику данных и продуктовый анализ: что мы на самом деле принимаем, нажимая «согласен», как устроены продукты, которые живут на наших данных, и как думать о продукте до того, как его строить.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_cta', 'ru', 'Читать в Telegram', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.group_project', 'ru', 'Проектная работа', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.group_team', 'ru', 'Работа в команде', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.title', 'ru', 'Оценка нового продукта или направления', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.duration', 'ru', '2–4 недели', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.body', 'ru', 'Разбираюсь, для кого продукт и какую задачу решает. Изучаю сегмент, альтернативы клиента и экономику. Вместе с основателем формулирую функцию продукта и границы первой версии.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.result', 'ru', 'Стратегия разработки: что делаем первым и в каком порядке, какие метрики и бюджет, что проверяем до того, как писать код. И вердикт по направлению: запускать, подождать или переделать замысел.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.involvement', 'ru', 'Респондентов и доступ к данным обеспечиваете вы.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.inside', 'ru', '- Сегмент и альтернативы, которыми клиент пользуется сейчас
- Интервью с аудиторией, включая тех, кто не купил
- Экономика на одну страницу
- Границы первой версии и порядок разработки', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.privacy_label', 'ru', 'Конфиденциальность', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('privacy.title', 'ru', 'Конфиденциальность', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('privacy.body', 'ru', '**Кто обрабатывает данные.** Сюзана Тевдорадзе, {email}.

**Что и зачем собирается.** Форма на сайте передаёт мне имя, адрес почты и текст сообщения — только чтобы ответить вам. Запись на консультацию проходит через Google Calendar по его условиям. Статистика посещений — Cloudflare Web Analytics: без cookies и без идентификации посетителей, только агрегированные показатели.

**Сколько хранится.** Сообщения — пока идёт переписка и не дольше 12 месяцев после её окончания, затем удаляются.

**Ваши права.** Вы можете запросить копию своих данных, их исправление или удаление — напишите на {email}.

**Cookies.** Сайт ставит одну техническую cookie с выбранным языком. Трекинговых cookies нет.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.telegram_label', 'ru', 'Telegram', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.action_note', 'ru', '20–40 минут онлайн, бесплатно.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.copy_label', 'ru', 'Копировать', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.copy_ok', 'ru', 'Скопировано', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.copy_selected', 'ru', 'Выделено', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_sending', 'ru', 'Отправляю…', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.name', 'en', 'Syuzana Tevdoradze', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.role', 'en', 'Technical Product Owner · AI and data products', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('site.description', 'en', 'Technical product lead for AI and data products: what to build, how to get it to production, and at what economics.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.situations', 'en', 'Tasks', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.formats', 'en', 'Ways to work', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.process', 'en', 'How I work', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.experience', 'en', 'Experience', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.pricing', 'en', 'Pricing', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('nav.contact', 'en', 'Contact', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.role', 'en', 'Technical Product Owner · AI and data products', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.title', 'en', 'Strategy and growth of AI products', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.lead', 'en', 'I''m a product lead with a technical background. I work on AI and data products: set priorities, assess the economics and the technical constraints, and drive delivery together with the team. I usually start with focus: the product''s function, the main pain, the market and the segment. Then the numbers: will the product pay back, the goals (OKR/KPI) and the roadmap. On that basis the founder decides whether to launch, grow or stop.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.cta', 'en', 'Book a free call', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.note', 'en', 'A first consultation, 20–40 minutes online: you describe the task, I say how I can help and whether you need me at all.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.contacts_label', 'en', 'Get in touch', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.title', 'en', 'What people come with', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('problems.items', 'en', '- Before launching an AI product you need to assess demand, technical feasibility and economics to make the investment decision.
- You need a clear development plan: what we build first, what comes next, what it costs, and which metrics will show it is working.
- An AI feature is being built into the product, say recognition, recommendations or an assistant. Deadlines slip, quality falls short of what is needed, spending on models and labelling grows. You need to decide whether to continue, change the approach or stop.
- It is unclear what customers will pay for, and whether the product pays back once infrastructure, labelling, manual checks and support are counted.
- There is no product manager on the team. The founder or the tech lead needs help with research, priorities and managing development.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.title', 'en', 'Ways to work', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.intro', 'en', 'Two project formats and one inside the team. We start with a free first consultation, then fix scope, timeline and price in writing.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.involvement_label', 'en', 'What I need from you', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.result_label', 'en', 'Result', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.inside_label', 'en', 'What''s inside', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.title', 'en', 'Audit of a live AI product', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.duration', 'en', '1–2 weeks', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.body', 'en', 'I examine model and data quality, real usage and the cost of running the product. I find what is in the way and what can be left alone.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.inside', 'en', '- What customers actually use and pay for, and what is dead weight
- What accuracy the models reach on real data and exactly where they fail
- What each customer costs to serve: infrastructure, labelling, manual checks, support
- What in the architecture blocks development and in what order to change it', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.involvement', 'en', 'Access to the system, data and metrics; two or three sessions with the team.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.audit.result', 'en', 'A rework plan: what to fix, what to drop, in what order, with effort and running-cost estimates. And a verdict: continue, change the approach, or stop.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.title', 'en', 'Part-time product lead', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.duration', 'en', '4 or 8 days a month', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.body', 'en', 'I take the product work on: priorities, research, requirements for the developers, acceptance of the result, coordination with the team.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.inside', 'en', '- Priorities and roadmap
- Research and metrics
- Requirements and acceptance
- Decision economics, including the cost of AI', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.involvement', 'en', 'Scope of responsibility and goals are agreed before we start; we begin with one paid month.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.fractional.result', 'en', 'The product gets an owner: decisions are made, requirements are written, development follows the plan. When the time comes, I help hire a permanent product lead.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.title', 'en', 'How it works', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.steps', 'en', '- A first consultation, free, 20–40 minutes: you describe the task, I say how I can help.
- A letter with scope, timeline and price. At the agreed scope the price doesn''t change.
- The work, with a short weekly update.
- A final session and a written report.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('process.principles', 'en', '- Before we start, we write down what will count as failure.
- In the report I mark separately what the data confirms and what remains an assumption.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.title', 'en', 'Experience', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.intro', 'en', 'A few results from recent years. Companies are not named; details are in the CV.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.items', 'en', '- AI monitoring for greenhouses: of more than ten detection models we kept the four that worked and rebuilt labelling. Average production accuracy went from 0.6 to 0.9, manual annotation fell by about 95%.
- Multi-tenant infrastructure: a move to shared services cut cloud cost per customer by roughly 10x and turned the unit economics positive.
- Government analytics: an NLP system for 200–250 thousand citizen requests a year, doing classification, entity extraction and routing. Processing became about 5x faster, with a person making the final call.
- Mobility data: moving from row-based to vector-based storage took a report from about three days to an hour and a half.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('experience.types', 'en', 'Most often this is computer vision and NLP in production, data platforms, legacy systems and the economics of early-stage AI products.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.bio', 'en', 'I''m a product lead with a technical background. I help find the product''s focus and decide whether it is worth doing. I research its value, the market, the audience and the competition. I work out whether the product pays back, and define how it should be built. I write the growth strategy and see development through to launch.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('card.qr_title', 'en', 'Scan to save my contact', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('card.qr_note', 'en', 'Opens a vCard on the phone, no typing needed. Useful when this page is on a screen someone else is looking at.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('about.cv_label', 'en', 'Download CV (PDF)', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.title', 'en', 'Pricing', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.intro', 'en', 'The rate is **from €100 an hour**, single tasks from two hours. Project scope is estimated in hours up front and fixed in writing.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.columns', 'en', 'Format | Scope | Duration', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.rows', 'en', 'First consultation | 20–40 minutes, free | –
Consultation | 1 hour, €150 | within a week
Consultation with a written review | from 3 hours, from €350 | within a week
Single task | from 2 hours | by agreement
Audit of a live AI product | from 20 hours | 1–2 weeks
Assessment of a new product or direction | from 30 hours | 2–4 weeks
Part-time product lead | 4 or 8 days a month | from 1 month
Full time | full days | on request', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('pricing.note', 'en', 'The final sum, scope and timeline are fixed in a written proposal after the first consultation. At the agreed scope the sum doesn''t change. The proposal states whether any taxes are added.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.title', 'en', 'Contact', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.body', 'en', 'Send me a couple of lines about the task; I reply within two working days. Or book the free first consultation straight away.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.booking_label', 'en', 'Book the free consultation', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.email_label', 'en', 'Email', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_title', 'en', 'Or briefly, right here', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_name', 'en', 'Name', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_email', 'en', 'Email', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_message', 'en', 'Briefly, what''s the situation?', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_send', 'en', 'Send', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_ok', 'en', 'Thank you. I''ll reply within two working days.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_error', 'en', 'Couldn''t send. Please email me instead.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_unavailable', 'en', 'Form sending is not available yet. Contact me via:', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_line', 'en', 'A channel on data ethics and product analysis.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.linkedin_label', 'en', 'LinkedIn', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.github_label', 'en', 'GitHub', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_label', 'en', 'Telegram channel', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.calendar_label', 'en', 'Calendar', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.title', 'en', 'There''s no such page', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('notfound.body', 'en', 'Back to the [home page](/en/).', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_title', 'en', 'The channel: «I accept the terms»', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_body', 'en', 'I write about data ethics and product analysis: what we really accept when we click "agree", how products that live on our data are built, and how to think about a product before building it.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.channel_cta', 'en', 'Read on Telegram', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.group_project', 'en', 'Project work', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.group_team', 'en', 'Work inside the team', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.title', 'en', 'Assessment of a new product or direction', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.duration', 'en', '2–4 weeks', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.body', 'en', 'I work out who the product is for and which task it solves. I study the segment, the customer''s alternatives and the economics. Together with the founder I define the product''s function and the boundaries of the first version.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.result', 'en', 'A development strategy: what we build first and in what order, which metrics and budget, what we test before writing code. And a verdict on the direction: launch, wait, or rethink.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.involvement', 'en', 'Respondents and access to data come from you.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('formats.evaluate.inside', 'en', '- Segment and the alternatives customers use today
- Interviews with the audience, including those who didn''t buy
- One-page economics
- First-version boundaries and the order of development', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.privacy_label', 'en', 'Privacy', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('privacy.title', 'en', 'Privacy', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('privacy.body', 'en', '**Who processes the data.** Syuzana Tevdoradze, {email}.

**What is collected and why.** The form on this site sends me your name, email address and message — only so I can reply. Booking a consultation goes through Google Calendar under its terms. Visit statistics come from Cloudflare Web Analytics: no cookies, no visitor identification, aggregate figures only.

**How long it is kept.** Messages — for the duration of our correspondence and no longer than 12 months after it ends; then they are deleted.

**Your rights.** You can request a copy of your data, a correction or deletion — write to {email}.

**Cookies.** The site sets one technical cookie with your chosen language. There are no tracking cookies.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('footer.telegram_label', 'en', 'Telegram', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('hero.action_note', 'en', '20–40 minutes online, no charge.', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.copy_label', 'en', 'Copy', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.copy_ok', 'en', 'Copied', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.copy_selected', 'en', 'Selected', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contact.form_sending', 'en', 'Sending…', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.email', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.linkedin', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.github', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.telegram', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.channel', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES ('contacts.booking_url', '*', '{{SET_IN_ADMIN}}', '1970-01-01T00:00:00Z');
