// Generates migrations/0002_seed.sql from content/seed/*.json.
// The JSON files are the source of truth for the default copy; the SQL is derived.
// `INSERT OR IGNORE` means re-running the migration never overwrites admin edits.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const seedDir = path.join(root, "content", "seed");
const out = path.join(root, "migrations", "0002_seed.sql");

const files = [
  ["ru", "ru.json"],
  ["en", "en.json"],
  ["*", "shared.json"],
];

const sql = (s) => `'${String(s).replace(/'/g, "''")}'`;
const lines = [
  "-- GENERATED by scripts/build-seed.mjs from content/seed/*.json — do not edit by hand.",
  "-- Default copy. INSERT OR IGNORE keeps any value already edited in the admin.",
];

for (const [lang, file] of files) {
  const values = JSON.parse(await readFile(path.join(seedDir, file), "utf8"));
  for (const [key, value] of Object.entries(values)) {
    lines.push(
      `INSERT OR IGNORE INTO content (key, lang, value, updated_at) VALUES (${sql(key)}, ${sql(lang)}, ${sql(value)}, '1970-01-01T00:00:00Z');`,
    );
  }
}

await writeFile(out, lines.join("\n") + "\n");
console.log(`wrote ${path.relative(root, out)} (${lines.length - 2} rows)`);
